// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XCOPYMEM_H
#define XCOPYMEM_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xcopymem_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_BaseAddress;
} XCopymem_Config;
#endif

typedef struct {
    u32 Ctrl_BaseAddress;
    u32 IsReady;
} XCopymem;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XCopymem_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XCopymem_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XCopymem_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XCopymem_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XCopymem_Initialize(XCopymem *InstancePtr, u16 DeviceId);
XCopymem_Config* XCopymem_LookupConfig(u16 DeviceId);
int XCopymem_CfgInitialize(XCopymem *InstancePtr, XCopymem_Config *ConfigPtr);
#else
int XCopymem_Initialize(XCopymem *InstancePtr, const char* InstanceName);
int XCopymem_Release(XCopymem *InstancePtr);
#endif

void XCopymem_Start(XCopymem *InstancePtr);
u32 XCopymem_IsDone(XCopymem *InstancePtr);
u32 XCopymem_IsIdle(XCopymem *InstancePtr);
u32 XCopymem_IsReady(XCopymem *InstancePtr);
void XCopymem_EnableAutoRestart(XCopymem *InstancePtr);
void XCopymem_DisableAutoRestart(XCopymem *InstancePtr);

void XCopymem_Set_dst(XCopymem *InstancePtr, u32 Data);
u32 XCopymem_Get_dst(XCopymem *InstancePtr);
void XCopymem_Set_src(XCopymem *InstancePtr, u32 Data);
u32 XCopymem_Get_src(XCopymem *InstancePtr);
void XCopymem_Set_bytes(XCopymem *InstancePtr, u64 Data);
u64 XCopymem_Get_bytes(XCopymem *InstancePtr);

void XCopymem_InterruptGlobalEnable(XCopymem *InstancePtr);
void XCopymem_InterruptGlobalDisable(XCopymem *InstancePtr);
void XCopymem_InterruptEnable(XCopymem *InstancePtr, u32 Mask);
void XCopymem_InterruptDisable(XCopymem *InstancePtr, u32 Mask);
void XCopymem_InterruptClear(XCopymem *InstancePtr, u32 Mask);
u32 XCopymem_InterruptGetEnabled(XCopymem *InstancePtr);
u32 XCopymem_InterruptGetStatus(XCopymem *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
