// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xcopymem.h"

extern XCopymem_Config XCopymem_ConfigTable[];

XCopymem_Config *XCopymem_LookupConfig(u16 DeviceId) {
	XCopymem_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCOPYMEM_NUM_INSTANCES; Index++) {
		if (XCopymem_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCopymem_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCopymem_Initialize(XCopymem *InstancePtr, u16 DeviceId) {
	XCopymem_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCopymem_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCopymem_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

