webtalk_init -webtalk_dir /storage/Documenti/Didattica/hpc/esercitazioni/hpc_eserc_02/design/design.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-05-14 16:39:06" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211447596_1777545082_0_246" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "259slrbo4dt2oc796ap7j7qgo1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_31" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1060.048 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8,223 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1557842061000" -context "sdk\\\\bsp/1557842061000"
webtalk_add_data -client sdk -key hwid -value "1556279333000" -context "sdk\\\\bsp/1557842061000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1557842061000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1557842061000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1557842061000"
webtalk_add_data -client sdk -key uid -value "1557842074000" -context "sdk\\\\application/1557842074000"
webtalk_add_data -client sdk -key hwid -value "1556279333000" -context "sdk\\\\application/1557842074000"
webtalk_add_data -client sdk -key bspid -value "1557842061000" -context "sdk\\\\application/1557842074000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1557842074000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1557842074000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1557842074000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1557842074000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1557842074000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1557842074000"
webtalk_add_data -client sdk -key projSize -value "188.28515625" -context "sdk\\\\application/1557842074000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1557844746402"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1557844746402"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1557844746402"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1557844746402"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1557844746402"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1557844746402"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1557844746402"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1557844746402"
webtalk_transmit -clientid 4199796329 -regid "211447596_1777545082_0_246" -xml /storage/Documenti/Didattica/hpc/esercitazioni/hpc_eserc_02/design/design.sdk/webtalk/usage_statistics_ext_sdk.xml -html /storage/Documenti/Didattica/hpc/esercitazioni/hpc_eserc_02/design/design.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /storage/Documenti/Didattica/hpc/esercitazioni/hpc_eserc_02/design/design.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
