set_property PACKAGE_PIN T21 [get_ports {led}]
set_property PACKAGE_PIN T22 [get_ports {ap_start_led}]
set_property PACKAGE_PIN F22 [get_ports {ap_start}]
set_property PACKAGE_PIN T18 [get_ports {reset_rtl}]

set_property IOSTANDARD  LVCMOS33 [get_ports {led}]
set_property IOSTANDARD  LVCMOS33 [get_ports {ap_start_led}]
set_property IOSTANDARD  LVCMOS33 [get_ports {ap_start}]
set_property IOSTANDARD  LVCMOS33 [get_ports {sys_clock}]
set_property IOSTANDARD  LVCMOS33 [get_ports {reset_rtl}]
