// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcopymem.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCopymem_CfgInitialize(XCopymem *InstancePtr, XCopymem_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCopymem_Start(XCopymem *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_AP_CTRL) & 0x80;
    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCopymem_IsDone(XCopymem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCopymem_IsIdle(XCopymem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCopymem_IsReady(XCopymem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCopymem_EnableAutoRestart(XCopymem *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_AP_CTRL, 0x80);
}

void XCopymem_DisableAutoRestart(XCopymem *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_AP_CTRL, 0);
}

void XCopymem_Set_dst(XCopymem *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_DST_DATA, Data);
}

u32 XCopymem_Get_dst(XCopymem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_DST_DATA);
    return Data;
}

void XCopymem_Set_src(XCopymem *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_SRC_DATA, Data);
}

u32 XCopymem_Get_src(XCopymem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_SRC_DATA);
    return Data;
}

void XCopymem_Set_bytes(XCopymem *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_BYTES_DATA, (u32)(Data));
    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_BYTES_DATA + 4, (u32)(Data >> 32));
}

u64 XCopymem_Get_bytes(XCopymem *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_BYTES_DATA);
    Data += (u64)XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_BYTES_DATA + 4) << 32;
    return Data;
}

void XCopymem_InterruptGlobalEnable(XCopymem *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_GIE, 1);
}

void XCopymem_InterruptGlobalDisable(XCopymem *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_GIE, 0);
}

void XCopymem_InterruptEnable(XCopymem *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_IER);
    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_IER, Register | Mask);
}

void XCopymem_InterruptDisable(XCopymem *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_IER);
    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_IER, Register & (~Mask));
}

void XCopymem_InterruptClear(XCopymem *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCopymem_WriteReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_ISR, Mask);
}

u32 XCopymem_InterruptGetEnabled(XCopymem *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_IER);
}

u32 XCopymem_InterruptGetStatus(XCopymem *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCopymem_ReadReg(InstancePtr->Ctrl_BaseAddress, XCOPYMEM_CTRL_ADDR_ISR);
}

